# Use an official Python runtime as a parent image
FROM python:3.11-alpine

# Install the MySQL client to be able to use it in the standby script.
RUN apk add --no-cache mysql-client

# Set the working directory in the container to /app
WORKDIR /app

# Copy the contents of the local app/ directory to the /app directory in the container
COPY app/ ./app

# Copy requirements.txt at the /app working directory
COPY requirements.txt .

# Copy the wait-for-db.sh script and set execution permissions
COPY --chmod=+x scripts/wait-for-db.sh ./scripts/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Update pip
RUN pip install --no-cache-dir --upgrade pip

# Expose port 5000
EXPOSE 5000

# Sets the CMD command to correctly execute the wait-for-db.sh script
CMD sh ./scripts/wait-for-db.sh && flask db upgrade && flask run --host=0.0.0.0 --port=5000 --reload --debug
