# Use an official Python runtime as a parent image
FROM python:3.11-alpine

# Instala el cliente de MySQL para poder usarlo en el script de espera
RUN apk add --no-cache mysql-client

# Establece el directorio de trabajo en el contenedor en /app
WORKDIR /app

# Copia el contenido del directorio local app/ al directorio /app en el contenedor
COPY app/ ./app

# Copia requirements.txt en el directorio de trabajo /app
COPY requirements.txt .

# Copia el script wait-for-db.sh y establece los permisos de ejecución
COPY --chmod=+x scripts/wait-for-db.sh ./scripts/

# Instala los paquetes necesarios especificados en requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Actualiza pip
RUN pip install --no-cache-dir --upgrade pip

# Expone el puerto 5000
EXPOSE 5000

# Ajusta el comando CMD para ejecutar correctamente el script wait-for-db.sh
CMD sh ./scripts/wait-for-db.sh && flask db upgrade && flask run --host=0.0.0.0 --port=5000 --reload --debug
