- hosts: all
  become: true

  tasks:
    - name: Add deadsnakes PPA (for installing Python 3.12)
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: yes

    - name: Update the system and install Python 3.12 and dependencies
      apt:
        name:
          - python3.12
          - python3.12-venv
          - python3.12-distutils
          - mariadb-client
        state: present

    - name: Install pip and setuptools for Python 3.12 from source
      shell: |
        wget https://bootstrap.pypa.io/get-pip.py
        python3.12 get-pip.py
      args:
        executable: /bin/bash

    - name: Upgrade pip and setuptools for Python 3.12
      shell: |
        python3.12 -m pip install --upgrade pip setuptools
      args:
        executable: /bin/bash

    - name: Remove existing virtual environment if it exists
      file:
        path: "{{ working_dir }}venv"
        state: absent
        force: yes

    - name: Set up the Python 3.12 virtual environment
      command: python3.12 -m venv {{ working_dir }}venv
      args:
        creates: "{{ working_dir }}venv/bin/activate"

    - name: Activate the virtual environment and install dependencies
      shell: |
        source {{ working_dir }}venv/bin/activate
        pip install --upgrade pip
        cd {{ working_dir }}
        pip install -r requirements.txt
        pip install -e ./
      args:
        executable: /bin/bash
