FROM runtime AS worker

# Copy scripts and set permissions
COPY --chmod=0755 scripts/wait-for-db.sh ./scripts/
COPY --chmod=0755 scripts/init-testing-db.sh ./scripts/

# Copy worker processing script
COPY docker/redis/worker.py /app/worker.py

# Worker start command
CMD ["python", "worker.py"]
