services:
      
  nginx:
    volumes:
      - ./nginx/nginx.prod.ssl.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./public:/var/www:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    volumes:
      - ./public:/var/www:rw
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - uvlhub_network
