"""add_doi_mapping_and_webhook

Revision ID: 002
Revises: 
Create Date: 2024-07-08 12:38:55.095000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.Inspector.from_engine(conn)

    if 'doi_mapping' not in inspector.get_table_names():
        op.create_table('doi_mapping',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dataset_doi_old', sa.String(length=120), nullable=True),
        sa.Column('dataset_doi_new', sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'webhook' not in inspector.get_table_names():
        op.create_table('webhook',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook')
    op.drop_table('doi_mapping')
    # ### end Alembic commands ###
