"""add statistics module

Revision ID: 011
Revises: 010
Create Date: 2024-10-15 11:01:19.816245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011'
down_revision = '010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasets_viewed', sa.Integer(), nullable=True),
    sa.Column('feature_models_viewed', sa.Integer(), nullable=True),
    sa.Column('datasets_downloaded', sa.Integer(), nullable=True),
    sa.Column('feature_models_downloaded', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
