"""empty message

Revision ID: 1e62574db52c
Revises: f78493544732
Create Date: 2023-06-19 15:04:11.324697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e62574db52c'
down_revision = 'f78493544732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=100), nullable=True))
        batch_op.alter_column('orcid',
               existing_type=mysql.VARCHAR(length=19),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('orcid',
               existing_type=mysql.VARCHAR(length=19),
               nullable=False)
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
