"""empty message

Revision ID: 2db3ee7b992d
Revises: 12887f86875d
Create Date: 2023-06-21 08:06:42.102214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2db3ee7b992d'
down_revision = '12887f86875d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_download_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.Column('download_cookie', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('download_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_record',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('download_date', mysql.DATETIME(), nullable=False),
    sa.Column('download_cookie', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], name='download_record_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='download_record_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('dataset_download_record')
    # ### end Alembic commands ###
