"""empty message

Revision ID: 47be69e6e2d4
Revises: ee680f773075
Create Date: 2025-09-21 17:15:31.909148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47be69e6e2d4'
down_revision = 'ee680f773075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('orcid',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=19),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('orcid',
               existing_type=sa.String(length=19),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
