"""empty message

Revision ID: 50ebf91dd306
Revises: 619b958229a5
Create Date: 2023-05-31 10:03:41.627823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50ebf91dd306'
down_revision = '619b958229a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.drop_column('dataset_doi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_doi', mysql.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
