"""empty message

Revision ID: 619b958229a5
Revises: f9f6f1563b3f
Create Date: 2023-05-30 19:07:22.420886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '619b958229a5'
down_revision = 'f9f6f1563b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('file_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('data_set_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_set_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('file_ibfk_1', 'data_set', ['data_set_id'], ['id'])
        batch_op.drop_column('feature_model_id')

    # ### end Alembic commands ###
