"""empty message

Revision ID: 65cb9814e59a
Revises: a6163cfa55c6
Create Date: 2023-05-22 12:05:30.002440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cb9814e59a'
down_revision = 'a6163cfa55c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ds_meta_data_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ds_meta_data', ['ds_meta_data_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ds_meta_data_id')

    # ### end Alembic commands ###
