"""updates_fk

Revision ID: 8a96e53e7e32
Revises: 47be69e6e2d4
Create Date: 2025-12-15 10:28:05.573825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a96e53e7e32'
down_revision = '47be69e6e2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.alter_column('dataset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_model_dataset_id'))

    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.alter_column('dataset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
