"""empty message

Revision ID: ae495423077e
Revises: 65cb9814e59a
Create Date: 2023-05-22 12:08:22.551385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae495423077e'
down_revision = '65cb9814e59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fm_meta_data_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fm_meta_data', ['fm_meta_data_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fm_meta_data_id')

    # ### end Alembic commands ###
