"""empty message

Revision ID: e6a0afca179e
Revises: c262ea6c57b6
Create Date: 2023-06-08 19:19:33.198218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6a0afca179e'
down_revision = 'c262ea6c57b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('gnd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gnd', mysql.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
